// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv6zr6swZC7h3bwjn0TV93NNRbIZs0-cc',
    appId: '1:198695485559:web:83b0309a10b9be94e68672',
    messagingSenderId: '198695485559',
    projectId: 'social-network-platform-641a6',
    authDomain: 'social-network-platform-641a6.firebaseapp.com',
    storageBucket: 'social-network-platform-641a6.firebasestorage.app',
    measurementId: 'G-Q9S9G8VN7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV2XvyD-5DDJVfQLGbRu4pBe7rfSSslU4',
    appId: '1:198695485559:android:11c08410d9b06619e68672',
    messagingSenderId: '198695485559',
    projectId: 'social-network-platform-641a6',
    storageBucket: 'social-network-platform-641a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC638thuNKFkF9h3Dy8ZVLSnaLw6bj3i7Q',
    appId: '1:198695485559:ios:116e058b5eaa478fe68672',
    messagingSenderId: '198695485559',
    projectId: 'social-network-platform-641a6',
    storageBucket: 'social-network-platform-641a6.firebasestorage.app',
    iosClientId: '198695485559-835i7ou81020cd9h24ilbel4j4kdoa8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialNetworkPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC638thuNKFkF9h3Dy8ZVLSnaLw6bj3i7Q',
    appId: '1:198695485559:ios:116e058b5eaa478fe68672',
    messagingSenderId: '198695485559',
    projectId: 'social-network-platform-641a6',
    storageBucket: 'social-network-platform-641a6.firebasestorage.app',
    iosClientId: '198695485559-835i7ou81020cd9h24ilbel4j4kdoa8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialNetworkPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv6zr6swZC7h3bwjn0TV93NNRbIZs0-cc',
    appId: '1:198695485559:web:6f82671efed0d69ae68672',
    messagingSenderId: '198695485559',
    projectId: 'social-network-platform-641a6',
    authDomain: 'social-network-platform-641a6.firebaseapp.com',
    storageBucket: 'social-network-platform-641a6.firebasestorage.app',
    measurementId: 'G-49XJ3YX8WL',
  );
}
